language: perl6

os:
  - linux

perl6:
  - latest

before_install:
    # Display travis OS name
  - echo $TRAVIS_OS_NAME

  # Debian-based libwkhtmltox installation
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then WKHTMLTOX_ARCHIVE=wkhtmltox_0.12.5-1.trusty_amd64.deb; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/$WKHTMLTOX_ARCHIVE; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -f -y ./$WKHTMLTOX_ARCHIVE; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then rm $WKHTMLTOX_ARCHIVE; fi

install:
  - rakudobrew build zef
  - zef install .
